<a href="https://colab.research.google.com/github/pervez72/1-Google-colab/blob/main/introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensor Basics

In [1]:
import torch

In [2]:
# 0D Tensor (Scalar)
scalar = torch.tensor(7)
print("0D Tensor (Scalar):", scalar)
print("Shape:", scalar.shape)  # কোনো dimension নেই



0D Tensor (Scalar): tensor(7)
Shape: torch.Size([])


In [3]:
# 1D Tensor (Vector)
vector = torch.tensor([1, 2, 3, 4])
print("\n1D Tensor (Vector):", vector)
print("Shape:", vector.shape)  # (4,)




1D Tensor (Vector): tensor([1, 2, 3, 4])
Shape: torch.Size([4])


In [4]:
# 2D Tensor (Matrix)
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])
print("\n2D Tensor (Matrix):\n", matrix)
print("Shape:", matrix.shape)  # (2, 3)



2D Tensor (Matrix):
 tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])


In [5]:


# 3D Tensor
tensor3d = torch.tensor([[[1, 2], [3, 4]],
                         [[5, 6], [7, 8]]])
print("\n3D Tensor:\n", tensor3d)
print("Shape:", tensor3d.shape)  # (2, 2, 2)





3D Tensor:
 tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Shape: torch.Size([2, 2, 2])


In [6]:

# 4D Tensor (CNN data format example: batch × channel × height × width)
tensor4d = torch.rand(10, 3, 28, 28)  # 10 images, 3 channels, 28x28 size
print("\n4D Tensor (Image batch): Shape =", tensor4d.shape)



4D Tensor (Image batch): Shape = torch.Size([10, 3, 28, 28])


In [7]:
# 5D Tensor (Video data format example: batch × channel × frames × height × width)
tensor5d = torch.rand(8, 3, 16, 64, 64)  # 8 videos, 3 channels, 16 frames, 64x64 resolution
print("\n5D Tensor (Video batch): Shape =", tensor5d.shape)


5D Tensor (Video batch): Shape = torch.Size([8, 3, 16, 64, 64])


**Temsor Index**

In [8]:
import torch
scalar = torch.tensor(42)
print(scalar.item())  # শুধু একটাই value, তাই .item() দিয়ে access করা হয়

42


In [9]:
vector = torch.tensor([10, 20, 30, 40, 50])
print(vector[0])   # প্রথম element → 10
print(vector[-1])  # শেষ element → 50
print(vector[1:4]) # slicing → [20, 30, 40]

tensor(10)
tensor(50)
tensor([20, 30, 40])


In [10]:
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

print(matrix[0, 0])   # Row=0, Col=0 → 1
print(matrix[1, 2])   # Row=1, Col=2 → 6
print(matrix[2])      # পুরো 3rd row → [7, 8, 9]
print(matrix[:, 1])   # পুরো 2nd column → [2, 5, 8]
print(matrix[0:2, 1:3])  # Sub-matrix slice


tensor(1)
tensor(6)
tensor([7, 8, 9])
tensor([2, 5, 8])
tensor([[2, 3],
        [5, 6]])


In [12]:
tensor3d = torch.tensor([[[1, 2], [3, 4]],
                         [[5, 6], [7, 8]]])
# Shape = (2, 2, 2)

print(tensor3d[0, 0, 1])   # 0th matrix, 0th row, 1st col → 2
print(tensor3d[1, 1, 0])   # 1st matrix, 1st row, 0th col → 7
print(tensor3d[0])         # পুরো প্রথম matrix
print(tensor3d[:, 1, :])   # প্রতিটা matrix-এর 2nd row
tensor4d = torch.rand(2, 3, 4, 4)
# 2 images, 3 channels, 4x4 size

print(tensor4d.shape)   # torch.Size([2, 3, 4, 4])
print(tensor4d[0, 0])   # প্রথম image-এর প্রথম channel (4x4 matrix)
print(tensor4d[1, 2, 3, 1])  # 2nd image, 3rd channel, row=3, col=1 element


tensor(2)
tensor(7)
tensor([[1, 2],
        [3, 4]])
tensor([[3, 4],
        [7, 8]])
torch.Size([2, 3, 4, 4])
tensor([[0.6870, 0.9306, 0.4954, 0.2996],
        [0.1021, 0.2012, 0.4227, 0.9416],
        [0.3554, 0.2793, 0.9947, 0.8680],
        [0.2561, 0.4824, 0.2432, 0.5273]])
tensor(0.4016)


In [13]:
tensor4d = torch.rand(2, 3, 4, 4)
# 2 images, 3 channels, 4x4 size

print(tensor4d.shape)   # torch.Size([2, 3, 4, 4])
print(tensor4d[0, 0])   # প্রথম image-এর প্রথম channel (4x4 matrix)
print(tensor4d[1, 2, 3, 1])  # 2nd image, 3rd channel, row=3, col=1 element


torch.Size([2, 3, 4, 4])
tensor([[0.4196, 0.0480, 0.3281, 0.5170],
        [0.9672, 0.4533, 0.1443, 0.8527],
        [0.2097, 0.7880, 0.6096, 0.1904],
        [0.0029, 0.3597, 0.7764, 0.9052]])
tensor(0.0422)
